### ISSUE TITLE
Chip Gaps and Cosmetic issues

### ISSUE THREAD

**Issue by mcoughlin** [mcoughlin/gwemopt#7]
Big cameras such as ZTF and PS1 have chip gaps such that each pointing should be dithered. Code should be modified to allow for such chip gaps. For example, ZTF has chips of size:

def get_tiles(ra_pointing, dec_pointing):

    pixel_size = 15 # microns
    plate_scale = 1 # arcsec/pixel
    plate_scale_deg = plate_scale / 3600.0
    tile_size = [6144,6160] # pixels
    gap_size = np.array([7,10])/(1e-3*pixel_size) # pixels

    idxs = [-3/2,-1/2,1/2,3/2]
    tiles = np.zeros((len(idxs),len(idxs),2))
    for i,idx in enumerate(idxs):
        for j,idy in enumerate(idxs):
            ra_center = ra_pointing + idx*(tile_size[0]+gap_size[0])*plate_scale_deg
            dec_center = dec_pointing + idy*(tile_size[1]+gap_size[1])*plate_scale_deg
            tiles[i,j,0] = ra_center
            tiles[i,j,1] = dec_center

    return tiles

**Comment by shaonghosh** [comment]
The ranked tiling code is now able to handle the chip gaps. However, I am working with David to implement this for the realistic FOV of ZTF. What I mean by that is in the past we have been using ad hoc tile boundaries computed based on the the tile center location (gotten from the ZTF fields file) and the FOV of the ZTF (which can be passed). However, this could have errors, even though very minute since ZTF’s FOV is very large. In a statistical analysis over a large sample this does not hurt us so much, however, for small number of events, we would want to fix this issue. What we are now working on is implementing this for realistic FOVs gotten from ZTF images themselves. David has already implemented this, I am working on absorbing this in the ranked tiling code. This requires some modification in the present version.

**Comment by mcoughlin** [comment]
@shaonghosh resolved this a long time ago.
